=== darkowlzz/peji/peji/page/schemas/shop-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://darkowlzz.space/peji/shop.schema.json",
    "title": "Shop Site Config",
    "description": "Peji site config for shop page",
    "type": "object",
    "properties": {
        "siteType": {
            "description": "Peji site type",
            "type": "string"
        },
        "title": {
            "description": "Title of the site",
            "type": "string"
        },
        "title-lead": {
            "description": "Head title/subtext",
            "type": "string"
        },
        "title-sublead": {
            "description": "Head subtitle/subtext",
            "type": "string"
        },
        "title-logo": {
            "description": "Site logo URL",
            "type": "string"
        },
        "primary-background": {
            "description": "Primary color of the site",
            "type": "string"
        },
        "secondary-background": {
            "description": "Secondary color of the site",
            "type": "string"
        },
        "info": {
            "description": "Informational content",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "description": "Name of the info item",
                        "type": "string"
                    },
                    "items": {
                        "description": "Info items",
                        "type": "array",
                        "properties": {
                            "name": {
                                "description": "Info item name",
                                "type": "string"
                            },
                            "link": {
                                "description": "Info item link",
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "link"
                        ],
                        "uniqueItems": true
                    }
                },
                "required": [
                    "title"
                ]
            }
        },
        "catalog": {
            "description": "Catalog of items in different categories",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "ID of a category",
                        "type": "string"
                    },
                    "category": {
                        "description": "Name of the category in catalog",
                        "type": "string"
                    },
                    "items": {
                        "description": "Items in the category",
                        "type": "array",
                        "properties": {
                            "id": {
                                "description": "ID of an item",
                                "type": "string"
                            },
                            "image": {
                                "description": "Item image link",
                                "type": "string"
                            },
                            "title": {
                                "description": "Item title",
                                "type": "string"
                            },
                            "description": {
                                "description": "Item description",
                                "type": "string"
                            },
                            "publishDate": {
                                "description": "Publish date of the item",
                                "type": "string"
                            },
                            "available": {
                                "description": "Availability of the item",
                                "type": "boolean"
                            },
                            "price": {
                                "description": "Price of the item",
                                "type": "number"
                            },
                            "button": {
                                "description": "Code snippet of the buy button",
                                "type": "string"
                            }
                        },
                        "required": [
                            "id",
                            "image",
                            "title",
                            "available",
                            "price"
                        ],
                        "uniqueItems": true
                    }
                },
                "required": [
                    "id",
                    "category"
                ],
                "uniqueItems": true
            }
        }
    },
    "required": [
        "siteType",
        "title"
    ]
}

=== darkowlzz/peji/tests/testdata/test_home_config.json
{
  "siteType": "HOME",
  "title": "DarkHoles",
  "title-lead": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "title-sublead": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam",
  "title-logo": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/face.png",
  "primary-background": "#f2f5f7",
  "secondary-background": "black",
  "info": [
    {
      "title": "Other Pages",
      "items": [
        {
          "name": "Gaming",
          "link": ""
        },
        {
          "name": "Music",
          "link": ""
        },
        {
          "name": "Books",
          "link": ""
        },
        {
          "name": "Thoughts",
          "link": ""
        }
      ]
    },
    {
      "title": "Social",
      "items": [
        {
          "name": "Twitter",
          "link": "https://twitter.com/darkowlzz",
          "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/Twitter_Logo_Blue.png"
        },
        {
          "name": "Discord",
          "link": "https://discordapp.com",
          "image": "https://discordapp.com/assets/2c21aeda16de354ba5334551a883b481.png"
        },
        {
          "name": "Twitch",
          "link": "https://twitch.com/darkowlzz",
          "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/Combo_Purple_RGB.png"
        },
        {
          "name": "Discord",
          "link": "https://discordapp.com",
          "image": "https://discordapp.com/assets/2c21aeda16de354ba5334551a883b481.png"
        },
        {
          "name": "Twitch",
          "link": "https://twitch.com/darkowlzz",
          "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/Combo_Purple_RGB.png"
        }
      ]
    },
    {
      "title": "About",
      "items": [
        {
          "name": "Privacy",
          "link": ""
        },
        {
          "name": "Terms",
          "link": ""
        }
      ]
    }
  ]
}

=== darkowlzz/peji/tests/testdata/test_update_shop.json
{
    "siteType": "SHOP",
    "title": "DarkHoles",
    "title-lead": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title-sublead": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam",
    "title-logo": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/face.png",
    "primary-background": "black",
    "secondary-background": "#f2f5f7",
    "info": [],
    "catalog": [
        {
            "id": "1",
            "category": "doloremque",
            "items": [
                {
                    "id": "1",
                    "image": "https://raw.githubusercontent.com/purdynerdy/artpics/master/pics/1.jpeg",
                    "title": "Look Deeper",
                    "description": "Watercolor - 15x20 inches",
                    "publishDate": "29th May, 2019",
                    "available": true,
                    "price": 300,
                    "button": "<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\" target=\"_top\"><input name=\"cmd\" type=\"hidden\" value=\"_s-xclick\"/><input name=\"hosted_button_id\" type=\"hidden\" value=\"PRPH7D5TPASA4\"/><input alt=\"PayPal - The safer, easier way to pay online!\" border=\"0\" name=\"submit\" src=\"https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif\" type=\"image\"/><img alt=\"\" border=\"0\" height=\"1\" src=\"https://www.paypalobjects.com/en_US/i/scr/pixel.gif\" width=\"1\"/></form>"
                },
                {
                    "id": "2",
                    "image": "https://raw.githubusercontent.com/purdynerdy/artpics/master/pics/2.jpeg",
                    "title": "Confrontation of Vulnerability",
                    "description": "Acrylic - 11x14 inches",
                    "publishDate": "29th May, 2019",
                    "available": true,
                    "price": 150,
                    "button": "<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\" target=\"_top\"><input name=\"cmd\" type=\"hidden\" value=\"_s-xclick\"/><input name=\"hosted_button_id\" type=\"hidden\" value=\"JLZFDXALR5VVW\"/><input alt=\"PayPal - The safer, easier way to pay online!\" border=\"0\" name=\"submit\" src=\"https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif\" type=\"image\"/><img alt=\"\" border=\"0\" height=\"1\" src=\"https://www.paypalobjects.com/en_US/i/scr/pixel.gif\" width=\"1\"/></form>"
                },
                {
                    "id": "3",
                    "image": "https://raw.githubusercontent.com/purdynerdy/artpics/master/pics/3.jpeg",
                    "title": "Unamused",
                    "description": "Acrylic - 5x7 inches",
                    "publishDate": "29th May, 2019",
                    "available": true,
                    "price": 50,
                    "button": "<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\" target=\"_top\"><input name=\"cmd\" type=\"hidden\" value=\"_s-xclick\"/><input name=\"hosted_button_id\" type=\"hidden\" value=\"SSEYT4F9WYTV6\"/><input alt=\"PayPal - The safer, easier way to pay online!\" border=\"0\" name=\"submit\" src=\"https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif\" type=\"image\"/><img alt=\"\" border=\"0\" height=\"1\" src=\"https://www.paypalobjects.com/en_US/i/scr/pixel.gif\" width=\"1\"/></form>"
                },
                {
                    "id": "4",
                    "image": "https://raw.githubusercontent.com/purdynerdy/artpics/master/pics/4.jpeg",
                    "title": "Jellyfish",
                    "description": "Acrylic - 5x7 inches",
                    "publishDate": "29th May, 2019",
                    "available": true,
                    "price": 50,
                    "button": "<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\" target=\"_top\"><input name=\"cmd\" type=\"hidden\" value=\"_s-xclick\"/><input name=\"hosted_button_id\" type=\"hidden\" value=\"BN6EX67ALHQ3S\"/><input alt=\"PayPal - The safer, easier way to pay online!\" border=\"0\" name=\"submit\" src=\"https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif\" type=\"image\"/><img alt=\"\" border=\"0\" height=\"1\" src=\"https://www.paypalobjects.com/en_US/i/scr/pixel.gif\" width=\"1\"/></form>"
                }
            ]
        },
        {
            "id": "2",
            "category": "aliqua",
            "items": [
                {
                    "id": "106",
                    "image": "https://media.discordapp.net/attachments/447673575617462293/575387386335199232/Untitled_Artwork.jpg",
                    "title": "voluptatem",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 9,
                    "button": ""
                },
                {
                    "id": "107",
                    "image": "https://media.tenor.com/images/b31aee1d14ea0e78467f0d4a8c9360a0/tenor.gif",
                    "title": "natus error",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 10,
                    "button": ""
                },
                {
                    "id": "108",
                    "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/laugh.gif",
                    "title": "Sed ut",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 20,
                    "button": ""
                },
                {
                    "id": "109",
                    "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/face.png",
                    "title": "laudantium",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 5,
                    "button": ""
                }
            ]
        }
    ]
}

=== darkowlzz/peji/docs/catalog-update/empty-catalog.json
{
    "siteType": "SHOP",
    "title": "some-title",
    "title-lead": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title-sublead": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam",
    "title-logo": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/face.png",
    "primary-background": "black",
    "secondary-background": "#f2f5f7",
    "info": [],
    "catalog": [
        {
            "id": "1",
            "category": "example",
            "items": []
        }
    ]
}

=== darkowlzz/peji/tests/testdata/test_config.json
{
    "siteType": "SHOP",
    "title": "DarkHoles",
    "title-lead": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title-sublead": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam",
    "title-logo": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/face.png",
    "primary-background": "black",
    "secondary-background": "#f2f5f7",
    "info": [
        {
            "title": "Other Pages",
            "items": [
                {
                    "name": "Gaming",
                    "link": ""
                },
                {
                    "name": "Music",
                    "link": ""
                },
                {
                    "name": "Books",
                    "link": ""
                },
                {
                    "name": "Thoughts",
                    "link": ""
                }
            ]
        },
        {
            "title": "Resources",
            "items": [
                {
                    "name": "Twitter",
                    "link": ""
                },
                {
                    "name": "Discord",
                    "link": ""
                },
                {
                    "name": "Twitch",
                    "link": ""
                }
            ]
        },
        {
            "title": "About",
            "items": [
                {
                    "name": "Privacy",
                    "link": ""
                },
                {
                    "name": "Terms",
                    "link": ""
                }
            ]
        }
    ],
    "catalog": [
        {
            "id": "1",
            "category": "doloremque",
            "items": [
                {
                    "id": "101",
                    "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/laugh.gif",
                    "title": "tempor incididunt",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 10,
                    "button": ""
                },
                {
                    "id": "102",
                    "image": "https://media.tenor.com/images/b31aee1d14ea0e78467f0d4a8c9360a0/tenor.gif",
                    "title": "magna aliqua",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 15,
                    "button": ""
                },
                {
                    "id": "103",
                    "image": "https://media.tenor.com/images/3fcc1b897b5dccb2a5edda6fb0d78e59/tenor.gif",
                    "title": "sit amet",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 12,
                    "button": ""
                },
                {
                    "id": "104",
                    "image": "https://media.discordapp.net/attachments/447673575617462293/575387386335199232/Untitled_Artwork.jpg",
                    "title": "omnis iste",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 20,
                    "button": ""
                },
                {
                    "id": "105",
                    "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/fallout-76-emote.jpg",
                    "title": "adipiscing elit",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 5,
                    "button": ""
                }
            ]
        },
        {
            "id": "2",
            "category": "aliqua",
            "items": [
                {
                    "id": "106",
                    "image": "https://media.discordapp.net/attachments/447673575617462293/575387386335199232/Untitled_Artwork.jpg",
                    "title": "voluptatem",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 9,
                    "button": ""
                },
                {
                    "id": "107",
                    "image": "https://media.tenor.com/images/b31aee1d14ea0e78467f0d4a8c9360a0/tenor.gif",
                    "title": "natus error",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 10,
                    "button": ""
                },
                {
                    "id": "108",
                    "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/laugh.gif",
                    "title": "Sed ut",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 20,
                    "button": ""
                },
                {
                    "id": "109",
                    "image": "https://raw.githubusercontent.com/darkowlzz/netlify-test/data/static/face.png",
                    "title": "laudantium",
                    "description": "Some description",
                    "publishDate": "1st Jan, 2019",
                    "available": true,
                    "price": 5,
                    "button": ""
                }
            ]
        }
    ]
}
